#!/usr/bin/env bash
#Run Nginx an Nginx

if [[ $(id -u) -ne 0 ]]; then
    echo "This script must be run as root" >&2
    exit 1
fi

sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/lib/nginx /var/www/html
service nginx restart
