#!/usr/bin/env bash
# installation of nginx and configureit to listen on port 80
# print "Hello World"

sudo apt-get update
sudo apt-get -y install nginx
echo 'Holberton School' | sudo tee /var/www/html/index.html
sudo service nginx start
